
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

import en from '@/components/translation/en.json';
import kn from '@/components/translation/kn.json';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const translations = {
  en,
  kn,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  return (
    <ClerkProvider>
    <html lang='en'>
      <body className={inter.className}>
        
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
